@echo off
REM ============================================================================
REM Sentinel Agent - Professional Installation Script (Windows Batch)
REM ============================================================================
REM This is a batch file version for users who prefer traditional cmd.exe
REM For better experience, use install.ps1 with PowerShell instead
REM ============================================================================

setlocal enabledelayedexpansion
color 0A
cls

echo.
echo ===============================================================================
echo              SENTINEL AGENT - COMPLETE INSTALLATION (BATCH VERSION)
echo ===============================================================================
echo.

REM Check if Python is installed
echo [STEP 1/6] Checking Python Installation...
python --version >nul 2>&1
if errorlevel 1 (
    color 0C
    echo.
    echo ERROR: Python is not installed or not in PATH
    echo Please download Python 3.10+ from https://www.python.org/downloads/
    echo.
    pause
    exit /b 1
)
for /f "tokens=*" %%i in ('python --version') do set PYTHON_VERSION=%%i
echo [OK] %PYTHON_VERSION%
echo.

REM Check if Ollama is installed
echo [STEP 2/6] Checking Ollama Installation...
ollama --version >nul 2>&1
if errorlevel 1 (
    color 0E
    echo [WARNING] Ollama is not installed or not in PATH
    echo Ollama is recommended for full functionality
    echo Download from: https://ollama.ai
    echo.
    color 0A
) else (
    for /f "tokens=*" %%i in ('ollama --version') do set OLLAMA_VERSION=%%i
    echo [OK] !OLLAMA_VERSION!
)
echo.

REM Remove existing venv
echo [STEP 3/6] Preparing Virtual Environment...
if exist venv (
    echo Removing existing virtual environment...
    rmdir /s /q venv >nul 2>&1
    echo [OK] Old environment removed
) else (
    echo [OK] No existing environment found
)
echo.

REM Create virtual environment
echo [STEP 4/6] Creating Virtual Environment...
python -m venv venv
if errorlevel 1 (
    color 0C
    echo.
    echo ERROR: Failed to create virtual environment
    echo.
    pause
    exit /b 1
)
echo [OK] Virtual environment created
echo.

REM Activate virtual environment and install
echo [STEP 5/6] Activating Virtual Environment and Upgrading Pip...
call venv\Scripts\activate.bat
python -m pip install --upgrade pip setuptools wheel --quiet
if errorlevel 1 (
    color 0C
    echo.
    echo ERROR: Failed to upgrade pip
    echo.
    pause
    exit /b 1
)
echo [OK] Pip upgraded
echo.

REM Install requirements
echo [STEP 6/6] Installing Project Dependencies...
echo This may take 2-5 minutes...
echo.
pip install -r requirements.txt
if errorlevel 1 (
    color 0C
    echo.
    echo ERROR: Failed to install dependencies
    echo.
    pause
    exit /b 1
)
echo.
echo [OK] All dependencies installed
echo.

REM Create .env if not exists
if not exist .env (
    echo Creating .env configuration file...
    (
        echo # Sentinel Agent Configuration
        echo # Generated by installation script
        echo.
        echo # Ollama Configuration
        echo OLLAMA_MODEL=llama3:8b
        echo OLLAMA_HOST=http://localhost:11434
        echo.
        echo # API Configuration
        echo API_HOST=127.0.0.1
        echo API_PORT=8000
        echo API_WORKERS=1
        echo.
        echo # Dashboard Configuration
        echo DASHBOARD_PORT=8501
        echo.
        echo # Logging Configuration
        echo LOG_LEVEL=INFO
    ) > .env
    echo [OK] .env file created
) else (
    echo [OK] .env file already exists
)
echo.

REM Create data directory
if not exist data (
    mkdir data
    echo [OK] Data directory created
)
echo.

color 0B
cls
echo.
echo ===============================================================================
echo                      ✓ INSTALLATION COMPLETE
echo ===============================================================================
echo.
echo NEXT STEPS:
echo ============================================================================
echo.
echo 1. ENSURE OLLAMA IS RUNNING:
echo    Open a terminal and run:
echo    ollama serve
echo.
echo 2. MAKE SURE LLAMA3 MODEL IS AVAILABLE:
echo    ollama pull llama3:8b
echo.
echo 3. START THE SYSTEM:
echo.
echo    TERMINAL 1 - Core System:
echo      venv\Scripts\activate.bat
echo      python main.py
echo.
echo    TERMINAL 2 - REST API (Optional):
echo      venv\Scripts\activate.bat
echo      python sentinel_api.py
echo      (Open http://localhost:8000 to access API)
echo.
echo    TERMINAL 3 - Dashboard (Optional):
echo      venv\Scripts\activate.bat
echo      streamlit run dashboard/web_dashboard.py
echo      (Open http://localhost:8501 in browser)
echo.
echo DOCUMENTATION:
echo  - README.md: Project overview
echo  - docs_markdown/: Detailed guides
echo  - docs_markdown/INDEX.md: Documentation index
echo.
echo ============================================================================
echo.
pause
