# ==============================================================================
# Sentinel Agent - Local Development Environment Setup (Windows)
# ==============================================================================
# CHANGE TRACKING (2026-02-23): Created setup script for Windows local development
# Fixes: Virtual environment creation, dependency installation, data directory setup
#
# This script sets up a Python virtual environment for running Sentinel Agent
# outside of Docker on your local Windows system.
#
# USAGE:
#   Right-click this file and select "Run with PowerShell"
#   Or from PowerShell: .\setup_local_env.ps1
#
# After running this script, activate the environment with:
#   .\venv\Scripts\Activate.ps1
# ==============================================================================

# Enable error handling
$ErrorActionPreference = "Stop"

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  Sentinel Agent - Local Environment Setup (Windows)" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

# Check Python installation
Write-Host "[1/6] Checking Python installation..." -ForegroundColor Yellow
try {
    $pythonVersion = python --version 2>&1
    if ($pythonVersion -match "Python (\d+\.\d+)") {
        Write-Host "✓ Found $pythonVersion" -ForegroundColor Green
    } else {
        throw "Python not found"
    }
} catch {
    Write-Host "✗ Python 3 not found" -ForegroundColor Red
    Write-Host "  Please install Python 3.8+ from https://python.org" -ForegroundColor Red
    Write-Host "  Make sure to check 'Add Python to PATH' during installation" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

# Check pip
Write-Host ""
Write-Host "[2/6] Checking pip..." -ForegroundColor Yellow
try {
    $pipVersion = python -m pip --version 2>&1
    Write-Host "✓ pip is available" -ForegroundColor Green
} catch {
    Write-Host "✗ pip not found" -ForegroundColor Red
    Write-Host "  Installing pip..." -ForegroundColor Yellow
    python -m ensurepip --upgrade
}

# Create virtual environment
Write-Host ""
Write-Host "[3/6] Creating virtual environment..." -ForegroundColor Yellow
if (Test-Path "venv") {
    Write-Host "⚠ Virtual environment already exists" -ForegroundColor Yellow
    $recreate = Read-Host "  Remove and recreate? [y/N]"
    if ($recreate -eq "y" -or $recreate -eq "Y") {
        Remove-Item -Recurse -Force venv
        python -m venv venv
        Write-Host "✓ Virtual environment recreated" -ForegroundColor Green
    } else {
        Write-Host "  Keeping existing virtual environment" -ForegroundColor Cyan
    }
} else {
    python -m venv venv
    Write-Host "✓ Virtual environment created" -ForegroundColor Green
}

# Activate virtual environment
Write-Host ""
Write-Host "[4/6] Activating virtual environment..." -ForegroundColor Yellow
& .\venv\Scripts\Activate.ps1
Write-Host "✓ Virtual environment activated" -ForegroundColor Green

# Upgrade pip
Write-Host ""
Write-Host "[5/6] Upgrading pip..." -ForegroundColor Yellow
python -m pip install --upgrade pip *> $null
Write-Host "✓ pip upgraded" -ForegroundColor Green

# Install requirements
Write-Host ""
Write-Host "[6/6] Installing dependencies..." -ForegroundColor Yellow
Write-Host "  This may take several minutes..." -ForegroundColor Cyan
try {
    pip install -r requirements.txt *> setup_install.log
    Write-Host "✓ All dependencies installed" -ForegroundColor Green
} catch {
    Write-Host "✗ Failed to install dependencies" -ForegroundColor Red
    Write-Host "  Check setup_install.log for details" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}

# Create data directories
Write-Host ""
Write-Host "[Extra] Setting up data directories..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path "data" *> $null
New-Item -ItemType Directory -Force -Path "logs" *> $null
Write-Host "✓ Created ./data and ./logs directories" -ForegroundColor Green

# Create .env file if it doesn't exist
if (-not (Test-Path ".env")) {
    Write-Host ""
    Write-Host "[Extra] Creating .env configuration file..." -ForegroundColor Yellow
    
    $envContent = @"
# Sentinel Agent - Local Development Configuration (Windows)
# CHANGE TRACKING (2026-02-23): Auto-generated by setup script

# Data paths (local development)
SENTINEL_DATA_DIR=./data
SENTINEL_LOG_DIR=./logs

# Ollama Configuration
OLLAMA_BASE_URL=http://127.0.0.1:11434
OLLAMA_MODEL=llama3:8b
OLLAMA_TIMEOUT=300

# Crew AI Timeout (seconds)
CREW_TIMEOUT=300

# Log files (Windows - adjust paths for your system)
# Note: On Windows, you may need to use WSL or generate test logs
AUTH_LOG=./data/auth.log
WEB_LOG=./data/access.log

# API Configuration
API_HOST=0.0.0.0
API_PORT=8000
"@
    
    $envContent | Out-File -FilePath ".env" -Encoding utf8
    Write-Host "✓ Created .env file" -ForegroundColor Green
    Write-Host "  Please edit .env to match your system" -ForegroundColor Yellow
} else {
    Write-Host "⚠ .env file already exists (not overwritten)" -ForegroundColor Yellow
}

# Success message
Write-Host ""
Write-Host "============================================================" -ForegroundColor Green
Write-Host "✓ Setup Complete!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host ""
Write-Host "  1. Activate the virtual environment:" -ForegroundColor White
Write-Host "     .\venv\Scripts\Activate.ps1" -ForegroundColor Green
Write-Host ""
Write-Host "  2. Edit .env file to configure paths:" -ForegroundColor White
Write-Host "     notepad .env" -ForegroundColor Green
Write-Host ""
Write-Host "  3. Make sure Ollama is running:" -ForegroundColor White
Write-Host "     ollama serve" -ForegroundColor Green
Write-Host ""
Write-Host "  4. Run the Sentinel Agent:" -ForegroundColor White
Write-Host "     python main.py" -ForegroundColor Green
Write-Host ""
Write-Host "  5. Or run the CLI dashboard:" -ForegroundColor White
Write-Host "     python dashboard/cli_dashboard.py" -ForegroundColor Green
Write-Host ""
Write-Host "  6. Or run the web dashboard:" -ForegroundColor White
Write-Host "     streamlit run dashboard/web_dashboard.py" -ForegroundColor Green
Write-Host ""
Write-Host "Deactivate virtual environment when done:" -ForegroundColor White
Write-Host "  deactivate" -ForegroundColor Green
Write-Host ""

Read-Host "Press Enter to exit"
