#!/bin/bash
# ==============================================================================
# Sentinel Agent - Local Development Environment Setup (Linux/macOS)
# ==============================================================================
# CHANGE TRACKING (2026-02-23): Created setup script for local development
# Fixes: Virtual environment creation, dependency installation, data directory setup
#
# This script sets up a Python virtual environment for running Sentinel Agent
# outside of Docker on your local Linux/Ubuntu/macOS system.
#
# USAGE:
#   chmod +x setup_local_env.sh
#   ./setup_local_env.sh
#
# After running this script, activate the environment with:
#   source venv/bin/activate
# ==============================================================================

set -e  # Exit on error

echo "============================================================"
echo "  Sentinel Agent - Local Environment Setup"
echo "============================================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check Python version
echo "[1/6] Checking Python version..."
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}✗ Python 3 not found${NC}"
    echo "  Please install Python 3.8+ first:"
    echo "  sudo apt install python3 python3-venv python3-pip"
    exit 1
fi

PYTHON_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1,2)
echo -e "${GREEN}✓ Found Python $PYTHON_VERSION${NC}"

# Check if venv module is available
echo ""
echo "[2/6] Checking python3-venv..."
if ! python3 -m venv --help &> /dev/null; then
    echo -e "${YELLOW}⚠ python3-venv not installed${NC}"
    echo "  Installing python3-venv..."
    sudo apt install -y python3-venv python3-full 2>/dev/null || {
        echo -e "${RED}✗ Failed to install python3-venv${NC}"
        echo "  Please run: sudo apt install python3-venv python3-full"
        exit 1
    }
fi
echo -e "${GREEN}✓ python3-venv available${NC}"

# Create virtual environment
echo ""
echo "[3/6] Creating virtual environment..."
if [ -d "venv" ]; then
    echo -e "${YELLOW}⚠ Virtual environment already exists${NC}"
    read -p "  Remove and recreate? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf venv
        python3 -m venv venv
        echo -e "${GREEN}✓ Virtual environment recreated${NC}"
    else
        echo "  Keeping existing virtual environment"
    fi
else
    python3 -m venv venv
    echo -e "${GREEN}✓ Virtual environment created${NC}"
fi

# Activate virtual environment
echo ""
echo "[4/6] Activating virtual environment..."
source venv/bin/activate
echo -e "${GREEN}✓ Virtual environment activated${NC}"

# Upgrade pip
echo ""
echo "[5/6] Upgrading pip..."
python -m pip install --upgrade pip > /dev/null 2>&1
echo -e "${GREEN}✓ pip upgraded${NC}"

# Install requirements
echo ""
echo "[6/6] Installing dependencies..."
echo "  This may take a few minutes..."
pip install -r requirements.txt > setup_install.log 2>&1 || {
    echo -e "${RED}✗ Failed to install dependencies${NC}"
    echo "  Check setup_install.log for details"
    exit 1
}
echo -e "${GREEN}✓ All dependencies installed${NC}"

# Create data directory
echo ""
echo "[Extra] Setting up data directory..."
mkdir -p data logs
echo -e "${GREEN}✓ Created ./data and ./logs directories${NC}"

# Create .env file if it doesn't exist
if [ ! -f ".env" ]; then
    echo ""
    echo "[Extra] Creating .env configuration file..."
    cat > .env << 'EOF'
# Sentinel Agent - Local Development Configuration
# CHANGE TRACKING (2026-02-23): Auto-generated by setup script

# Data paths (local development)
SENTINEL_DATA_DIR=./data
SENTINEL_LOG_DIR=./logs

# Ollama Configuration
OLLAMA_BASE_URL=http://127.0.0.1:11434
OLLAMA_MODEL=llama3:8b
OLLAMA_TIMEOUT=300

# Crew AI Timeout (seconds)
CREW_TIMEOUT=300

# Log files (adjust paths for your system)
AUTH_LOG=/var/log/auth.log
WEB_LOG=/var/log/apache2/access.log

# API Configuration
API_HOST=0.0.0.0
API_PORT=8000
EOF
    echo -e "${GREEN}✓ Created .env file${NC}"
    echo -e "${YELLOW}  Please edit .env to match your system paths${NC}"
else
    echo -e "${YELLOW}⚠ .env file already exists (not overwritten)${NC}"
fi

# Success message
echo ""
echo "============================================================"
echo -e "${GREEN}✓ Setup Complete!${NC}"
echo "============================================================"
echo ""
echo "Next steps:"
echo ""
echo "  1. Activate the virtual environment:"
echo -e "     ${GREEN}source venv/bin/activate${NC}"
echo ""
echo "  2. Edit .env file to configure paths:"
echo -e "     ${GREEN}nano .env${NC}"
echo ""
echo "  3. Make sure Ollama is running:"
echo -e "     ${GREEN}ollama serve${NC}"
echo ""
echo "  4. Run the Sentinel Agent:"
echo -e "     ${GREEN}python3 main.py${NC}"
echo ""
echo "  5. Or run the CLI dashboard:"
echo -e "     ${GREEN}python3 dashboard/cli_dashboard.py${NC}"
echo ""
echo "  6. Or run the web dashboard:"
echo -e "     ${GREEN}streamlit run dashboard/web_dashboard.py${NC}"
echo ""
echo "Deactivate virtual environment when done:"
echo -e "  ${GREEN}deactivate${NC}"
echo ""
